### ISSUE TITLE
You should try your code before release

### ISSUE THREAD

**Issue by javaherobrine** [Mandarancio/QB2Draw#1]
There is a pure virtual function not overridden,it's b2Draw::DrawTransform.Please test the demo before releasing it.And you called a nonexistent function DrawDebugData() in 67th line of mainwindow.cpp,you should call world->DrawDebug() instead of calling world->DrawDebugData().
The version of Box2D is 1.4.1
The version of Qt is 5.9.9
The standard of C++ is C++11

**Comment by Mandarancio** [comment]
Hi I updated the code to Qt5 and latest Box2D version (the method missing was DrawPoint).

Let me know if it does work now.

Cheers,
Martino
